### ISSUE TITLE
Impossible to open VCF v4.2 files..

### ISSUE THREAD

**Issue by fpichon** [paulhager/smart-phase#10]
Hi, thanks for your tool, seems useful.
However, I could not open any VCF file... Have the following error:
`Exception in thread "main" java.lang.Exception: While parsing filtered variants, tried to split using '\t' but failed. Please ensure your file is tab-seperated, or ends in .csv if it is comma separated.`
`at smartPhase.FilteredVariantReader.<init>(FilteredVariantReader.java:94)`

My VCF is generated by GATK and the version is:
`##fileformat=VCFv4.2`
Thanks for your help.

**Comment by timjeske** [comment]
Dear fpichon, 

thank you for your interest in our tool!

I guess, the error message is due to the fact that you didn't provide a gene region BED file. SmartPhase does generally not phase all variants within the filtered variants file. Either it generates all pairs of variants in defined gene regions (option -g) or you directly provide preselected pairs. As it seems you did not provide a gene region file, SmartPhase assumes that you provide preselected pairs in a tab separated file causing this error message. You can check our use case to see how it works [here](https://github.com/paulhager/smart-phase#use-case).

I hope I could help. Let us know if you still run into problems!

Best regards
Tim
